export const home = {
  catchphrase: "踊って 貴方は開花する...",
  caption: "通常のレッスン風景 （入門基礎クラス）",
  categories: [
    { href: "/belly-dance", label: "ベリーダンス", tone: "pink" as const },
    { href: "/yoga", label: "ヨガ ＆ピラティス", tone: "teal" as const },
  ],
  whatsNewTitle: "What's New?",
  upcomingTitle: "UPCOMING EVENT",
  notices: [
    { href: "/schedule", text: "◆ レッスンスケジュールはこちら" },
    { href: "/trial", text: "◎各クラス随時体験募集中" },
    {
      href: "/schedule",
      text: "◆ ヨガ＆ピラティスＺｏｏｍオンラインレッスン実施中",
    },
  ],
  lineNote:
    "（上記各レッスンにお申込みの方は、 LINE公式アカウントご登録いただき、メッセージをお待ちしております。）",
  reservaLabel: "予約システムはこちらから",
  events: [
    "☆永田充さんから学ぶ （９０分）",
    "アラブの打楽器☆ダラブッカ クラス",
    "",
    "・８月３０日（日）１８：００～１９：３０",
    "・９月２７日（日）１８：００～１９：３０",
    "",
    "ジルで学ぶ♪アラブ音楽のリズム",
    "ワークショップ",
    "・８月３０日（日）１７：００～１８：３０",
    "",
    "Eva.Oriental カルチャー・サロン",
    "２０２６．１月",
    "『RAKUDA - club - 』発足！",
    "",
    "第２段",
    "『Undar the Moon』キャンドルワークショップ",
    "・９月２６日（土）",
    "詳細は決まり次第お知らせいたします。",
    "",
    "ご予約はLINE公式アカウントにメッセージお願いします。",
  ],
  credit: "紀三井寺・龍宮乙姫伝説実行委員会",
};
